{{- $domain := include "redis-apps.domain" . }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace }}-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://mminichino.github.io/helm-charts
      targetRevision: {{ .Values.cluster.chart.version }}
      chart: redis-cluster
      helm:
        values: |
          name: "{{ .Values.namespace }}-cluster"
          namespace: {{ .Values.namespace | quote }}
          license: {{ .Values.cluster.values.license | quote }}
          username: {{ .Values.cluster.values.username | quote }}
          node:
            count: {{ .Values.cluster.values.node.count }}
            cpu: {{ .Values.cluster.values.node.cpu | quote }}
            memory: {{ .Values.cluster.values.node.memory }}
            disk: {{ .Values.cluster.values.node.disk }}
          ingress:
            enabled: {{ .Values.cluster.values.ingress.enabled }}
            type: {{ .Values.cluster.values.ingress.type }}
          storage:
            class: {{ .Values.cluster.values.storage.class }}
          dns:
            domain: {{ $domain | quote }}
          tls:
          {{- toYaml .Values.cluster.values.tls | nindent 12 }}
          syncer:
          {{- toYaml .Values.cluster.values.syncer | nindent 12 }}
          externalSecret:
            enabled: {{ .Values.cluster.values.externalSecret.enabled }}
            store:
              kind: {{ .Values.cluster.values.externalSecret.store.kind }}
              name: {{ .Values.cluster.values.externalSecret.store.name }}
            key: {{ .Values.cluster.values.externalSecret.key }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
