{{- range .Values.databases }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.namespace }}-{{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ $.Values.project }}
  sources:
    - repoURL: https://mminichino.github.io/helm-charts
      targetRevision: {{ $.Values.database.chart.version }}
      chart: redis-database
      helm:
        values: |
          name: {{ .name }}
          namespace: {{ $.Values.namespace | quote }}
          password: {{ .password }}
          cluster: "{{ $.Values.namespace }}-cluster"
          memory: {{ .memory }}
          replication: {{ .replication }}
          shards: {{ .shards }}
          placement: {{ .placement }}
          port: {{ .port }}
          eviction: {{ .eviction }}
          ossCluster: {{ .ossCluster }}
          proxyPolicy: {{ .proxyPolicy }}
          persistence: {{ .persistence }}
          {{- if .modules }}
          modules:
            {{- range .modules }}
            - {{ . }}
            {{- end }}
          {{- end }}
          ingress:
            type: {{ .ingress.type }}
          tls:
            enabled: {{ .tls.enabled }}
            {{- if .tls.certificates }}
            certificates:
              {{- range .tls.certificates }}
              - {{ . }}
              {{- end }}
            {{- else }}
            certificates: []
            {{- end }}
          {{- if .dns.domain }}
          dns:
            domain: {{ .dns.domain | quote }}
          {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
{{- end }}
