{{- range .Values.databases }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.namespace }}-{{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ $.Values.project }}
  sources:
    - repoURL: https://mminichino.github.io/helm-charts
      targetRevision: {{ $.Values.database.chart.version }}
      chart: redis-database
      helm:
        values: |
          name: {{ .name }}
          namespace: {{ $.Values.namespace | quote }}
          username: {{ .username | default "default" }}
          password: {{ .password | default "" }}
          passwordSecret: {{ .passwordSecret | default "" }}
          cluster: "{{ $.Values.namespace }}-cluster"
          memory: {{ .memory | default "1GB" }}
          replication: {{ .replication | default true }}
          shards: {{ .shards | default 1 }}
          placement: {{ .placement | default "sparse" }}
          port: {{ .port | default 12000 }}
          eviction: {{ .eviction | default "noeviction" }}
          ossCluster: {{ .ossCluster | default false }}
          proxyPolicy: {{ .proxyPolicy | default "all-master-shards" }}
          persistence: {{ .persistence | default "aofEverySecond" }}
          version: {{ .version | default "latest" }}
          {{- if and .ossExporter .ossExporter.enabled }}
          ossExporter:
            enabled: {{ .ossExporter.enabled }}
            image: {{ .ossExporter.image | default "codelry/redis-exporter" }}
            version: {{ .ossExporter.version | default "v1.79.0" }}
          {{- end }}
          {{- if .modules }}
          modules:
            {{- range .modules }}
            - {{ . }}
            {{- end }}
          {{- end }}
          ingress:
            type: {{ .ingress.type }}
          tls:
            enabled: {{ .tls.enabled }}
            {{- if .tls.certificates }}
            certificates:
              {{- range .tls.certificates }}
              - {{ . }}
              {{- end }}
            {{- else }}
            certificates: []
            {{- end }}
          {{- if .dns.domain }}
          dns:
            domain: {{ .dns.domain | quote }}
          {{- end }}
          {{- if and .externalSecret .externalSecret.enabled }}
          externalSecret:
            enabled: {{ .externalSecret.enabled }}
            store:
              kind: {{ .externalSecret.store.kind | default "ClusterSecretStore" }}
              name: {{ .externalSecret.store.name }}
            key: {{ .externalSecret.key }}
          {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
