apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace }}-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://helm.redis.io
      targetRevision: {{ .Values.operator.version }}
      chart: redis-enterprise-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: admission-tls
      namespace: {{ .Values.namespace }}
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: "redis-enterprise-admission-{{ .Values.namespace }}"
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
