project: redis-apps
environment: redis
namespace: redis
monitoring: false

cluster:
  chart:
    version: 0.2.1
  values:
    license: ""
    username: "demo@redis.com"
    node:
      count: 3
      cpu: "4"
      memory: 8Gi
      disk: 32Gi
    ingress:
      enabled: false
      type: "nginx"
    storage:
      class: "premium-rwo"
    dns:
      domain: ""
    tls:
      name: "proxy"
      certificate: ""
      key: ""
      secret: ""
    syncer:
      certificate: ""
      key: ""
      secret: ""
    externalSecret:
      enabled: false
      store:
        kind: ClusterSecretStore
        name: ""
      key: ""

database:
  chart:
    version: 0.1.20

databases:
  - name: "redb"
    username: "default"
    password: ""
    passwordSecret: ""
    cluster: "redis-enterprise-cluster"
    memory: "1GB"
    replication: true
    shards: 1
    placement: sparse
    port: 12000
    eviction: noeviction
    ossCluster: false
    proxyPolicy: all-master-shards
    persistence: aofEverySecond
    version: "latest"
    ossExporter:
      enabled: false
      image: "codelry/redis-exporter"
      version: "v1.79.0"
    modules:
      - ReJSON
      - search
      - timeseries
    ingress:
      type: "none"
    tls:
      enabled: false
      certificates: []
    dns:
      domain: ""
    externalSecret:
      enabled: false
      store:
        kind: ClusterSecretStore
        name: ""
      key: ""
  - name: "rdidb"
    password: ""
    passwordSecret: ""
    cluster: "redis-enterprise-cluster"
    memory: "256MB"
    replication: true
    shards: 1
    placement: sparse
    port: 12001
    eviction: noeviction
    ossCluster: false
    proxyPolicy: all-master-shards
    persistence: aofEverySecond
    version: "latest"
    ossExporter:
      enabled: false
      image: "codelry/redis-exporter"
      version: "v1.79.0"
    modules:
      - ReJSON
      - search
      - timeseries
    ingress:
      type: "none"
    tls:
      enabled: false
      certificates: []
    dns:
      domain: ""
    externalSecret:
      enabled: false
      store:
        kind: ClusterSecretStore
        name: ""
      key: ""
